name: Publish Pelican Site CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: GitHub Pages Pelican Build Action
        uses: nelsonjchen/gh-pages-pelican-action@0.2.0
        env:
          PELICAN_THEME_FOLDER: custom_theme
          GH_PAGES_CNAME: artificiallyintelligent.info
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
